#!/usr/bin/env bash
set -e

# ============================================================
#  CopySnap - One-Click Setup Script
#  This script configures and launches your CopySnap instance.
# ============================================================

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}${BOLD}╔═══════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}║       CopySnap - Setup Wizard         ║${NC}"
echo -e "${BLUE}${BOLD}║    AI Copywriting SaaS Platform       ║${NC}"
echo -e "${BLUE}${BOLD}╚═══════════════════════════════════════╝${NC}"
echo ""

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed.${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Error: Node.js 18+ is required. You have $(node -v)${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node -v) detected${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Found existing .env file.${NC}"
    read -p "Overwrite it? (y/N): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "Keeping existing .env file."
        SKIP_ENV=true
    fi
fi

if [ "$SKIP_ENV" != "true" ]; then
    echo -e "${BOLD}Step 1: API Keys Configuration${NC}"
    echo ""

    # OpenAI Key
    echo -e "You need an OpenAI API key to power the AI content generation."
    echo -e "Get one at: ${BLUE}https://platform.openai.com/api-keys${NC}"
    echo ""
    read -p "Enter your OpenAI API key (sk-...): " OPENAI_KEY
    while [[ ! "$OPENAI_KEY" =~ ^sk- ]]; do
        echo -e "${RED}Invalid key format. It should start with 'sk-'${NC}"
        read -p "Enter your OpenAI API key: " OPENAI_KEY
    done
    echo -e "${GREEN}✓ OpenAI key configured${NC}"
    echo ""

    # YooKassa Keys
    echo -e "You need YooKassa credentials for payment processing."
    echo -e "Register at: ${BLUE}https://yookassa.ru${NC}"
    echo -e "Get Shop ID and Secret Key at: ${BLUE}https://yookassa.ru/my/shop-settings${NC}"
    echo -e "${YELLOW}(Press Enter to skip YooKassa setup - you can add it later)${NC}"
    echo ""

    read -p "Enter YooKassa Shop ID: " YOOKASSA_SHOP_ID
    YOOKASSA_SECRET=""

    if [ -n "$YOOKASSA_SHOP_ID" ]; then
        read -p "Enter YooKassa Secret Key (test_... or live_...): " YOOKASSA_SECRET
        echo ""
        echo -e "${GREEN}✓ YooKassa configured${NC}"
        echo ""
        echo -e "Don't forget to set up a webhook in YooKassa Dashboard:"
        echo -e "  URL: ${BOLD}https://your-domain.com/api/payment/webhook${NC}"
        echo -e "  Event: ${BOLD}payment.succeeded${NC}"
    else
        echo -e "${YELLOW}YooKassa skipped. App will work without payments.${NC}"
    fi

    # Generate JWT secret
    JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")

    # Write .env file
    cat > .env << EOF
# Auto-generated by setup.sh
OPENAI_API_KEY=${OPENAI_KEY}
JWT_SECRET=${JWT_SECRET}
YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET}
NEXT_PUBLIC_APP_URL=http://localhost:3000
DATABASE_URL="file:./dev.db"
EOF

    echo -e "${GREEN}✓ .env file created${NC}"
fi

echo ""
echo -e "${BOLD}Step 2: Installing dependencies...${NC}"
npm install

echo ""
echo -e "${BOLD}Step 3: Setting up database...${NC}"
npx prisma generate
npx prisma db push

echo ""
echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║        Setup Complete!                ║${NC}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════╝${NC}"
echo ""
echo -e "To start the app in development mode:"
echo -e "  ${BOLD}npm run dev${NC}"
echo ""
echo -e "Then open ${BLUE}http://localhost:3000${NC} in your browser."
echo ""
echo -e "To build for production:"
echo -e "  ${BOLD}npm run build && npm run start${NC}"
echo ""
echo -e "${YELLOW}Next steps to start earning:${NC}"
echo -e "  1. Deploy to a hosting provider (Railway, VPS)"
echo -e "  2. Set up your custom domain"
echo -e "  3. Configure YooKassa webhook for live payments"
echo -e "  4. Promote your tool on social media, Product Hunt, etc."
echo ""
